export const sheetHeading = [
  "userType",
  "firstName",
  "lastName",
  "describe",
  "title",
  "dateOfBirth",
  "email",
  "phone",
  "status",
  "total",
  "paymentDate",
  "buildingNumber",
  "subBuildingName",
  "buildingName",
  "streetName",
  "city",
  "country", // now working as post code
  "lender",
  "outstandingBalance",
  "contribute",
  "totalDebtLevel",
  "curCreditorRepayment",
  "totalLender",
  "newCreditorRepayment",
  "monthlySaving",
  "yearlySaving",
];
